### ISSUE TITLE
OpenLayers 3, D3.js

### ISSUE THREAD

**Issue by pecet86** [meetjspl/lublin#12]
Interaktywna Mapa Rowerowa lub z danymi rowerowymi na bazie [mirl.info.pl](mirl.info.pl)

Jak kogoś ciekawi mogę zaprezentować. Proszę o info zwrotne.

:/ nie mogę dodać label'a, więc proszę o "prezentacja" / "lightning talk"

**Comment by sptq** [comment]
Hej, 

Dzięki za zgłoszenie - mogę Ciebie zaprosić na szóste spotkanie jako lightning talk. Powiedz proszę ile trwa twoja prezentacja.

**Comment by pecet86** [comment]
@sptq dopasuje się może być 5 może i 15 min. Jak będzie zainteresowanie.

**Comment by sptq** [comment]
@pecet86 ok daje tobie 10 min. Podaj proszę imię i nazwisko to dodam Ciebie do agendy. Pamiętaj proszę że w prezentacji nie możesz umieścić żadnego lokowania firmy, w której pracujesz. Prezentację prezentujesz jako ty.

**Comment by pecet86** [comment]
@sptq Paweł Cal

Jeżeli chodzi ci o podaną stronę to robiona prywatnie i nieodpłatnie ale ok.
