### ISSUE TITLE
Gulp 4

### ISSUE THREAD

**Issue by verenichvlad** [meetjspl/lublin#7]
### Przykładowa agenda:
1. Automatyzacja zadań.
2. Wybór narzędzia do automatyzacji (Gulp/Grunt)
3. Przykłady automatyzacji codziennych zadań w Gulp.
4. Co nowego w Gulp 4.

**Comment by sptq** [comment]
Super :)
Mam tylko pytanie czy chcesz prezentacje czy lightning talk?

**Comment by verenichvlad** [comment]
Prezentacja lub lightning, zależy czy będą inni prelegenci i z jakim typem występu :)
